database_prod:
  dbname: "db_mysql"
  dbtable: "music"
database_test:
  dbname: "db_mysql"
  dbtable: "music"

# service_type should be NodePort, ClusterIP or LoadBalancer
service_type: LoadBalancer
replicas: 3

ingress:
  enabled: true

pod:
  image: "yuval597/myapp"  
  tag: "v3"                   
  target_port: 5001             
  port: 5001
