kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-svc #from RELEASE NAME
spec:
  type: {{ .Values.service_type }}
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.pod.port }} #from Values
    targetPort: {{ .Values.pod.target_port }}  #from values
