name: CI-CD

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Run Hello World JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Yuval"
  
  test-failure:
    runs-on: ubuntu-latest
    needs: hello

    steps:
      - name: fail test
        run: exit 1

  build:
    runs-on: ubuntu-latest
    needs: test-failure

    env:
      ENVIRONMENT: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment
        run: echo "We are in $ENVIRONMENT environment"
      
      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        run: docker build -t yuval597/k8slab:${{ github.run_number }} .

      - name: Docker push
        run: docker push yuval597/k8slab:${{ github.run_number }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: yuval597/GitOps
          token: ${{ secrets.GITOPS_TOKEN }}
          path: GitOps

      - name: Helm template
        run: |
          mkdir -p GitOps/k8slab/${ENVIRONMENT}

          helm template k8slab ./chart \
          --set pod.image=yuval597/k8slab \
          --set pod.tag=${{ github.run_number }} \
          > GitOps/k8slab/${ENVIRONMENT}/k8slab.yaml

      - name: Push to GitOps
        run: |
          cd GitOps
          git config user.name "yuval597"
          git config user.email "yuvaliko597@gmail.com"
          git add .
          git commit -m "Update ${ENVIRONMENT} deployment to image ${{ github.run_number }}" || echo "No changes to commit"
          git push
  
  slack-success:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps: 
      - name: Slack success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: alerts
          SLACK_USERNAME: Yuval Schreiber
          SLACK_TITLE: Success
          SLACK_MESSAGE: |
            Repository: ${{ github.repository }} 
            Branch: ${{ github.ref_name }} 
            Image: yuval597/k8slab:${{ github.run_number }} 
            Commit: ${{ github.sha }}
          SLACK_COLOR: good
  
  slack-failure:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps: 
      - name: Slack failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: alerts
          SLACK_USERNAME: Yuval Schreiber
          SLACK_TITLE: Failure
          SLACK_MESSAGE: |
            Repository: ${{ github.repository }} 
            Branch: ${{ github.ref_name }} 
            Image: yuval597/k8slab:${{ github.run_number }} 
            Commit: ${{ github.sha }}
          SLACK_COLOR: danger

      
