name: start

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Run Hello World JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Yuval"

  build:
    runs-on: ubuntu-latest
    needs: hello

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Docker login
        use: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        run: docker build -t yuval597/k8slab:${{ github.run_number }} .

      - name: Docker push
        run: docker push yuval597/k8slab:${{ github.run_number }}

      - name: Helm template
        run: helm template k8slab ./k8s
  
  slack-notify:
    runs-on: ubuntu-latest
    needs: build

    steps: 
      - name: Slack notify
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: alerts
          SLACK_USERNAME: Yuval Schreiber
          SLACK_TITLE: Notification
          SLACK_MESSAGE: |
            Repository: ${{ github.repository }} 
            Branch: ${{ github.ref_name }} 
            Image: yuval597/k8slab:${{ github.run_number }} 
            Commit: ${{ github.sha }}
          SLACK_COLOR: good
