name: start

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Run Hello World JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Yuval"

  build:
    runs-on: ubuntu-latest
    needs: hello

    steps:
      - name: Build app
        run: echo "Building"
  
  slack-notify:
    runs-on: ubuntu-latest
    needs: hello

    steps: 
      - name: Slack notify
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: alerts
          SLACK_USERNAME: Yuval Schreiber
          SLACK_TITLE: Notification
          SLACK_MESSAGE: "Pipeline test notification"
          SLACK_COLOR: good
